name: flutter_bluetooth_basic
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.1
  rxdart: ^0.23.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.2.2
  
flutter:
  plugin:
    androidPackage: com.tablemi.flutter_bluetooth_basic
    pluginClass: FlutterBluetoothBasicPlugin
